import fake from 'faker';

export const restaurant = [
  {
    id: 1,
    precision: 0.5,
    name: 'React Cafe',
    address: '123 Anywhere St',
    rating: fake.random.number({max: 5, min: 1, precision: 0.5}),
    thumbnailUrl: 'https://via.placeholder.com/150/8985dc',
  },
  {
    id: 2,
    name: 'Fancy Restaurant',
    address: '799 Main St',
    rating: fake.random.number({max: 5, min: 1, precision: 0.5}),
    thumbnailUrl: 'https://via.placeholder.com/150/5e12c6',
  },
  {
    id: 3,
    name: fake.company.companyName(),
    address: fake.address.streetAddress(),
    rating: fake.random.number({max: 5, min: 1, precision: 0.5}),
    thumbnailUrl: 'https://via.placeholder.com/150/45601a',
  },
  {
    id: 4,
    name: fake.company.companyName(),
    address: fake.address.streetAddress(),
    rating: fake.random.number({max: 5, min: 1, precision: 0.5}),
    thumbnailUrl: 'https://via.placeholder.com/150/e924e6',
  },
  {
    id: 5,
    name: fake.company.companyName(),
    address: fake.address.streetAddress(),
    rating: fake.random.number({max: 5, min: 1, precision: 0.5}),
    thumbnailUrl: 'https://via.placeholder.com/150/8f209a',
  },
  {
    id: 6,
    name: fake.company.companyName(),
    address: fake.address.streetAddress(),
    rating: fake.random.number({max: 5, min: 1, precision: 0.5}),
    thumbnailUrl: 'https://via.placeholder.com/150/5e3a73',
  },
  {
    id: 7,
    name: fake.company.companyName(),
    address: fake.address.streetAddress(),
    rating: fake.random.number({max: 5, min: 1, precision: 0.5}),
    thumbnailUrl: 'https://via.placeholder.com/150/474645',
  },
  {
    id: 8,
    name: fake.company.companyName(),
    address: fake.address.streetAddress(),
    rating: fake.random.number({max: 5, min: 1, precision: 0.5}),
    thumbnailUrl: 'https://via.placeholder.com/150/c984bf',
  },
  {
    id: 9,
    name: fake.company.companyName(),
    address: fake.address.streetAddress(),
    rating: fake.random.number({max: 5, min: 1, precision: 0.5}),
    thumbnailUrl: 'https://via.placeholder.com/150/392537',
  },
  {
    id: 10,
    name: fake.company.companyName(),
    address: fake.address.streetAddress(),
    rating: fake.random.number({max: 5, min: 1, precision: 0.5}),
    thumbnailUrl: 'https://via.placeholder.com/150/602b9e',
  },
  {
    id: 11,
    name: fake.company.companyName(),
    address: fake.address.streetAddress(),
    rating: fake.random.number({max: 5, min: 1, precision: 0.5}),
    thumbnailUrl: 'https://via.placeholder.com/150/372c93',
  },
  {
    id: 12,
    name: fake.company.companyName(),
    address: fake.address.streetAddress(),
    rating: fake.random.number({max: 5, min: 1, precision: 0.5}),
    thumbnailUrl: 'https://via.placeholder.com/150/a7c272',
  },
  {
    id: 13,
    name: fake.company.companyName(),
    address: fake.address.streetAddress(),
    rating: fake.random.number({max: 5, min: 1, precision: 0.5}),
    thumbnailUrl: 'https://via.placeholder.com/150/c70a4d',
  },
  {
    id: 14,
    name: fake.company.companyName(),
    address: fake.address.streetAddress(),
    rating: fake.random.number({max: 5, min: 1, precision: 0.5}),
    thumbnailUrl: 'https://via.placeholder.com/150/501fe1',
  },
  {
    id: 15,
    name: fake.company.companyName(),
    address: fake.address.streetAddress(),
    rating: fake.random.number({max: 5, min: 1, precision: 0.5}),
    thumbnailUrl: 'https://via.placeholder.com/150/35185e',
  },
  {
    id: 16,
    name: fake.company.companyName(),
    address: fake.address.streetAddress(),
    rating: fake.random.number({max: 5, min: 1, precision: 0.5}),
    thumbnailUrl: 'https://via.placeholder.com/150/c96cad',
  },
  {
    id: 17,
    name: fake.company.companyName(),
    address: fake.address.streetAddress(),
    rating: fake.random.number({max: 5, min: 1, precision: 0.5}),
    thumbnailUrl: 'https://via.placeholder.com/150/ea51da',
  },
  {
    id: 18,
    name: fake.company.companyName(),
    address: fake.address.streetAddress(),
    rating: fake.random.number({max: 5, min: 1, precision: 0.5}),
    thumbnailUrl: 'https://via.placeholder.com/150/4f5b8d',
  },
  {
    id: 19,
    name: fake.company.companyName(),
    address: fake.address.streetAddress(),
    rating: fake.random.number({max: 5, min: 1, precision: 0.5}),
    thumbnailUrl: 'https://via.placeholder.com/150/1e71a2',
  },
  {
    id: 20,
    name: fake.company.companyName(),
    address: fake.address.streetAddress(),
    rating: fake.random.number({max: 5, min: 1, precision: 0.5}),
    thumbnailUrl: 'https://via.placeholder.com/150/a88404',
  },
  {
    id: 21,
    name: fake.company.companyName(),
    address: fake.address.streetAddress(),
    rating: fake.random.number({max: 5, min: 1, precision: 0.5}),
    thumbnailUrl: 'https://via.placeholder.com/150/714582',
  },
  {
    id: 22,
    name: fake.company.companyName(),
    address: fake.address.streetAddress(),
    rating: fake.random.number({max: 5, min: 1, precision: 0.5}),
    thumbnailUrl: 'https://via.placeholder.com/150/7facef',
  },
  {
    id: 23,
    name: fake.company.companyName(),
    address: fake.address.streetAddress(),
    rating: fake.random.number({max: 5, min: 1, precision: 0.5}),
    thumbnailUrl: 'https://via.placeholder.com/150/907c53',
  },
];
